loading_quotes = [
    ('wat do? JAVASCRIPT Google Maps, handles multiple', 'Chris Shaw'),
    ('No action is required on your end :)', 'Ryan Greenland'),
    ('hows it going today big dawg?', 'Michael King'),
    ('Kool Aid Man', 'Jerod Badger'),
    ('ayeeee nice', 'Josh Martinez'),
    ('I bet there\'s something on the site that\'s causing it to bug out', 'Joseph Moore'),
    ('I don\'t know if I know that Pokémon...', 'Joseph Moore'),
    ('HAHAHAHAHAHAHAHAHAHAHAHAHAH', 'Chris Shaw'),
    ('you already know the password right?', 'Chris Shaw'),
    ('you have clearance Clarence', 'Chris Shaw'),
    ('you are a modern day hero', 'Chris Shaw'),
    ('iiiiii don\'t know? maybe it\'s in readthe.guide?', 'Chris Shaw'),
    ('STAY OFF MY TURF.', 'Jerod Badger'),
    ('I\'ve got a meeting in nine minutes.', 'Jerod Badger'),
    ('Weird. But, okay.', 'Jerod Badger'),
    ('Dopest dope.', 'Jerod Badger'),
    ('MUST DESTROY', 'Jerod Badger'),
    ('if you want to mess with those you totes can', 'Michael King'),
    ('they all look very quick and easy', 'Michael King'),
    ('forever immortalized', 'Michael King'),
    ('even after compressing- i got the same as the before score', 'Ryan Greenland'),
    ('I think it\'s a salmon-crested cockatoo', 'Joseph Moore'),
    ('I\'ve seen this once before but I can\'t remember the solution.', 'Joseph Moore'),
    ('bruh. why you breaking things', 'Joseph Moore'),
    ('Yay verily.', 'Joseph Moore'),
    ('lolol alright. I haven\'t even looked at them', 'Joshua Martinez'),
    ('noice', 'Joshua Martinez'),
    ('gad dang beaurocracy', 'Joey Puopolo'),
    ('can you send me a link to compressinator v2?', 'Alvin Go')
]